import { client } from '../../../lib/graphql'
import { emailTrigger, autoGenerateCart, statusLogger } from '../../../utils'
import { GET_CUSTOMERS_DETAILS } from '../graphql'

export const reminderMail = async (req, res) => {
   try {
      const { subscriptionOccurenceId } = req.body.payload
      const { subscriptionOccurences = [] } = await client.request(
         GET_CUSTOMERS_DETAILS,
         {
            id: subscriptionOccurenceId
         }
      )

      if (subscriptionOccurences.length === 0)
         return res.status(200).json({
            success: false,
            message: `No subscription occurence linked to id ${subscriptionOccurenceId}`
         })

      const [occurence] = subscriptionOccurences
      const { subscription = {}, subscriptionId } = occurence

      if (!subscriptionId)
         return res.status(200).json({
            success: false,
            message: `No subscription is linked to occurence id ${subscriptionOccurenceId}`
         })

      const { products = [] } = await client.request(GET_PRODUCTS, {
         subscriptionOccurenceId,
         subscriptionId
      })

      const { brand_customers = [] } = subscription

      if (brand_customers.length === 0)
         return res.status(200).json({
            success: false,
            message: `There are no brand customers yet linked to subscription id ${subscriptionId}`
         })

      await Promise.all(
         brand_customers.map(async customer => {
            try {
               const {
                  id,
                  keycloakId,
                  isAutoSelectOptOut,
                  subscriptionOccurences = [],
                  customerEmail
               } = customer

               await statusLogger({
                  keycloakId,
                  brand_customerId: id,
                  subscriptionOccurenceId,
                  message: `Initiating Reminder mails and Auto Generating system for subscriptionOcurrenceId - ${subscriptionOccurenceId} and brandCustomerId - ${id}`
               })

               if (
                  subscriptionOccurences.length > 0 &&
                  subscriptionOccurences[0].cartId != null &&
                  'itemCountValid' in subscriptionOccurences[0].validStatus &&
                  subscriptionOccurences[0].validStatus.itemCountValid
               ) {
                  const [occurence] = subscriptionOccurences
                  const { isAuto, isSkipped } = occurence

                  if (isSkipped === false) {
                     if (isAuto) {
                        await statusLogger({
                           keycloakId,
                           brand_customerId: id,
                           subscriptionOccurenceId,
                           message: `Cart is autoGenerated previously for brandCustomer - ${brandCustomerId}. Sending Email.`
                        })
                        await emailTrigger({
                           title: 'autoGenerateCart',
                           variables: {
                              brandCustomerId,
                              subscriptionOccurenceId
                           },
                           to: customerEmail.email
                        })
                     } else {
                        await statusLogger({
                           keycloakId,
                           brand_customerId: id,
                           subscriptionOccurenceId,
                           message: `Cart is generated by brand customer ${brandCustomerId}. Sending Email.`
                        })
                        await emailTrigger({
                           title: 'allSetCart',
                           variables: {
                              brandCustomerId,
                              subscriptionOccurenceId
                           },
                           to: customerEmail.email
                        })
                     }
                  } else {
                     await statusLogger({
                        keycloakId,
                        brand_customerId: id,
                        subscriptionOccurenceId,
                        message: `Brand Customer ${id} has skipped the week. Sending Email`
                     })
                     await emailTrigger({
                        title: 'weekSkipped',
                        variables: {
                           brandCustomerId,
                           subscriptionOccurenceId
                        },
                        to: customerEmail.email
                     })
                  }
               } else {
                  if (isAutoSelectOptOut) {
                     await statusLogger({
                        keycloakId,
                        brand_customerId: id,
                        subscriptionOccurenceId,
                        message: `Brand Customer ${brandCustomerId} doesn't have option to generate the cart. Sending Email`
                     })
                     await emailTrigger({
                        title: 'weekSkipped',
                        variables: {
                           brandCustomerId,
                           subscriptionOccurenceId
                        },
                        to: customerEmail.email
                     })
                  } else {
                     await autoGenerateCart({
                        keycloakId,
                        brand_customerId: id,
                        subscriptionOccurenceId,
                        products
                     })
                  }
               }
            } catch (error) {
               throw Error(error.message)
            }
         })
      )

      return res.status(200).json({
         success: true,
         message: 'Successfully sent the mail'
      })
   } catch (error) {
      console.log('Reminder email -> error', error)
      return res.status(400).json({ success: false, error: error.message })
   }
}

const GET_PRODUCTS = `
   query products($subscriptionOccurenceId: Int!, $subscriptionId: Int!) {
      products: subscription_subscriptionOccurence_product(
         where: {
            _or: [
               { subscriptionOccurenceId: { _eq: $subscriptionOccurenceId } }
               { subscriptionId: { _eq: $subscriptionId } }
            ]
         }
      ) {
         cartItem
      }
   }
`
