import { sendEmail } from '..'
import { client } from '../../lib/graphql'

export const addProductsToCart = async ({
   brandCustomerId,
   subscriptionOccurenceId,
   products
}) => {
   try {
      await statusLogger(
         brandCustomerId,
         subscriptionOccurenceId,
         'Adding Products To Cart'
      )
      const {
         brandCustomers: [
            {
               subscriptionOccurences: [
                  {
                     validStatus = {},
                     cartId,
                     isSkipped,
                     subscriptionOccurence = {}
                  }
               ] = []
            }
         ] = []
      } = await client.request(PENDING_PRODUCT_COUNT, {
         brandCustomerId,
         subscriptionOccurenceId
      })
      const method = require(`../../options/${
         subscriptionOccurence.subscriptionAutoSelectOption &&
         subscriptionOccurence.subscriptionAutoSelectOption
      }`)

      const sortedProducts = await method.default(products)
      let i = 0,
         count = validStatus.pendingProductsCount

      if (sortedProducts.length >= count) {
         while (i < count) {
            try {
               await client.request(INSERT_CART_ITEM, {
                  object: {
                     ...sortedProducts[i].cartItem,
                     cartId,
                     isAutoAdded: true
                  }
               })
            } catch (error) {
               throw Error(error.message)
            }
            i++
         }

         if (isSkipped) {
            await statusLogger(
               brandCustomerId,
               subscriptionOccurenceId,
               `Brand Customer ${brandCustomerId} has skipped the week. Sending Email`
            )
            await sendEmail({
               brandCustomerId,
               subscriptionOccurenceId,
               fileName: 'weekSkipped'
            })
         } else {
            await statusLogger(
               brandCustomerId,
               subscriptionOccurenceId,
               `Products have been added for ${brandCustomerId} and ${subscriptionOccurenceId}. Sending Email`
            )
            await sendEmail({
               brandCustomerId,
               subscriptionOccurenceId,
               fileName: 'autoGeneratedCart'
            })
         }
      } else {
         await statusLogger(brandCustomerId, subscriptionOccurenceId, {
            error: `Not enought products in ${subscriptionOccurenceId} `
         })
      }
   } catch (error) {
      throw Error(error.message)
   }
}

export const statusLogger = async (
   brandCustomerId,
   subscriptionOccurenceId,
   log
) => {
   await client.request(UPDATE_CUSTOMER_LOGS, {
      brandCustomerId,
      subscriptionOccurenceId,
      object: {
         logs: log
      }
   })
}

export const UPDATE_CUSTOMER_LOGS = `mutation StatusLogger($object: subscription_subscriptionOccurence_customer_prepend_input!, $brandCustomerId: Int!, $subscriptionOccurenceId: Int!) {
  update_subscription_subscriptionOccurence_customer(where: {brand_customerId: {_eq: $brandCustomerId}, subscriptionOccurenceId: {_eq: $subscriptionOccurenceId }}, _prepend: $object) {
    returning {
      logs
    }
  }
}

`

export const INSERT_CART_ITEM = `
   mutation createCartItem($object: order_cartItem_insert_input!) {
      createCartItem(object: $object) {
         id
      }
   }
`

const PENDING_PRODUCT_COUNT = `
query pendingProductCount($brandCustomerId: Int!, $subscriptionOccurenceId: Int!) {
  brandCustomers(where: {id: {_eq: $brandCustomerId}}) {
    subscriptionOccurences(where: {subscriptionOccurenceId: {_eq: $subscriptionOccurenceId}}) {
      validStatus
      cartId
      isSkipped
      subscriptionOccurence {
        subscriptionAutoSelectOption
        subscriptionId
      }
    }
  }
}

`
